apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: lanchonete-tc2
type: Opaque
data:
  DB_USER: "YWRtaW4=" # admin
  DB_PASSWORD: "YWRtaW4=" # admin
  DB_NAME: "bGFuY2hvbmV0ZV9kYg==" # lanchonete_db
  ACCESS_TOKEN: "VEVTVC0yMzI0MjEyOTg5MzMyNzIxLTA1MjEyMS1mZjZlMDE1NjM0M2RlYjgyNjQ2MzY2OTMwZjYyMmVjYS0zNzQwMTc5OTQ=" # TEST-2324212989332721-052121-ff6e0156343deb82646366930f622eca-374017994
  DATABASE_URL: "cG9zdGdyZXNxbDovL2FkbWluOmFkbWluQHBvc3RncmVzLWRiLXNlcnZpY2UubGFuY2hvbmV0ZS1kYi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2xhbmNob25ldGVfZGI/c2NoZW1hPXB1YmxpYw==" # postgresql://admin:admin@postgres-db-service.lanchonete-db.svc.cluster.local:5432/lanchonete_db?schema=public