apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: lanchonete-tc2
type: Opaque
data:
  DB_USER: "YWRtaW4="
  DB_PASSWORD: "YWRtaW4="
  DB_NAME: "bGFuY2hvbmV0ZV9kYg=="
  ACCESS_TOKEN: "VEVTVC0yMzI0MjEyOTg5MzMyNzIxLTA1MjEyMS1mZjZlMDE1NjM0M2RlYjgyNjQ2MzY2OTMwZjYyMmVjYS0zNzQwMTc5OTQ="
  DATABASE_URL: "cG9zdGdyZXNxbDovL2FkbWluOmFkbWluQHBvc3RncmVzLWRiLXNlcnZpY2UubGFuY2hvbmV0ZS1kYi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2xhbmNob25ldGVfZGI/c2NoZW1hPXB1YmxpYw=="